import type { Metadata } from 'next';
import { Geist, Geist_Mono as GeistMono } from 'next/font/google';

import './globals.css';
import { AppBar } from '@/widgets/app-bar';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = GeistMono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout(props: Readonly<{ children: React.ReactNode }>) {
    const {
        children,
    } = props;
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AppBar />
                <div className="flex flex-col items-center justify-center p-[24px]">
                    {children}
                </div>
            </body>
        </html>
    );
}
